#!/bin/bash

echo -n "Enter any service name to check: "
read service

command=$(which $service)
status=$?

if [[ $status -eq 0 ]]; then
    echo "$service is installed"
    echo "$service version is $($service -v)"
else
    echo "$service is not installed"
fi
